# Generated by Django 4.1.3 on 2022-11-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='num_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
