# Generated by Django 4.1.3 on 2022-11-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshortener', '0002_link_num_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='num_views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
